### ISSUE TITLE
变量未定义

### ISSUE THREAD

**Issue by xiang578** [gashero/gsnote#1]
https://github.com/gashero/gsnote/blob/a1b5b1f02d236e295037c43799faa72f5f50cdc0/gsnote/gstat.py#L45

**Comment by gashero** [comment]
刚刚修复了，这个功能用于确保所有的笔记是"\n"换行的，避免混杂"\r\n"换行。我之前的笔记都做过整理就无法进入这个流程，导致长期未发现。
